export const RESTAURANT_LIST_DATA = "RESTAURANT_LIST_DATA";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const EDIT_RESTAURANT = "EDIT_RESTAURANT";
export const ADD_MENU_ITEM = "ADD_MENU_ITEM";
