export default {
  products: [
    {
      key: "1",
      name: "Chaayoos - Meri Wali Chai",
      rating: 3.8,
      dt: 40,
      avgcost: 200,
      address: "New York No. 1 Lake Park",
      tags: ["Cafe", "Tea", "Fast Food", "Steet Food", "Desserts", "Beverages"],
    },
    {
      key: "2",
      name: "Biryani By Kilo",
      rating: 3.6,
      dt: 90,
      avgcost: 300,
      address: "London No. 1 Lake Park",
      tags: ["Biryani", "Mughlai", "kebab", "Hyderabadi"],
    },
    {
      key: "3",
      name: "Subway",
      rating: 3.8,
      dt: 37,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["Healthy Food", "Salad", "Sandwich", "Fast Food"],
    },
    {
      key: "4",
      name: "Burger King",
      rating: 3.3,
      dt: 49,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["Burger", "American"],
    },
    {
      key: "5",
      name: "Bikaneerwala",
      rating: 3.8,
      dt: 60,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["Mithai", "Street Food"],
    },
    {
      key: "6",
      name: "Donimos's Pizza",
      rating: 3.9,
      dt: 30,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["Pizza", "Fast Food"],
    },

    {
      key: "7",
      name: "Taco Bell",
      rating: 3.8,
      dt: 48,
      avgcost: 250,
      address: "Sidney No. 1 Lake Park",
      tags: ["Wraps", "Mexican", "Fast Food"],
    },
    {
      key: "8",
      name: "Joe Black",
      rating: 3.8,
      dt: 60,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["cool", "teacher"],
    },
    {
      key: "9",
      name: "Joe Black",
      rating: 3.8,
      dt: 40,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["cool", "teacher"],
    },
    {
      key: "10",
      name: "Joe Black",
      rating: 3.8,
      dt: 40,
      avgcost: 200,
      address: "Sidney No. 1 Lake Park",
      tags: ["cool", "teacher"],
    },
  ],
};
